version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
      day: wednesday
      time: "09:20"
      timezone: Australia/Sydney      
    groups:
      weekly-updates:
        patterns:
          - "*"
