#!/bin/bash

curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain=stable -y

echo '. $HOME/.cargo/env' >> ~/.bashrc
echo '. $HOME/.cargo/env' >> ~/.profile
source $HOME/.cargo/env

cargo install evcxr_jupyter --no-default-features
evcxr_jupyter --install
